#theme: jekyll-theme-slate
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme 
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-bootstrap-sass
  - jekyll-tidy


#title: [The title of your site]
#description: [A short description of your site's purpose]

#show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]


markdown: kramdown
highlighter: rouge
